"""created_at type change 2

Revision ID: 5f2c0288aa24
Revises: 9d9a1ff35439
Create Date: 2023-05-29 13:22:09.731126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f2c0288aa24"
down_revision = "9d9a1ff35439"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
