"""init

Revision ID: 76cb59adf300
Revises: 
Create Date: 2023-05-29 11:40:24.107062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76cb59adf300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_loc_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy_m', sa.Integer(), nullable=True),
    sa.Column('altitude_m', sa.Integer(), nullable=True),
    sa.Column('battery_per', sa.Integer(), nullable=True),
    sa.Column('battery_status', sa.Integer(), nullable=True),
    sa.Column('course_over_ground', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=2), nullable=True),
    sa.Column('tracker_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('vertical_accuracy_m', sa.Integer(), nullable=True),
    sa.Column('velocity_kmh', sa.Integer(), nullable=True),
    sa.Column('barometric_pressure_kpa', sa.Float(), nullable=True),
    sa.Column('poi_name', sa.String(), nullable=True),
    sa.Column('conn', sa.String(length=2), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('inregions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('inrids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('SSID', sa.String(), nullable=True),
    sa.Column('BSSID', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('monitoring_mode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_loc_data')
    # ### end Alembic commands ###
