"""created_at type change

Revision ID: 9d9a1ff35439
Revises: 5719fe5a2d63
Create Date: 2023-05-29 13:08:04.398587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d9a1ff35439"
down_revision = "5719fe5a2d63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
