"""location table name change

Revision ID: e1c5e45b959e
Revises: f8e30574bd95
Create Date: 2023-08-19 14:52:28.109400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1c5e45b959e'
down_revision = 'f8e30574bd95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc', sa.Integer(), nullable=True),
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('batt', sa.Integer(), nullable=True),
    sa.Column('bs', sa.Integer(), nullable=True),
    sa.Column('cog', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lon', sa.Double(), nullable=True),
    sa.Column('rad', sa.Integer(), nullable=True),
    sa.Column('t', sa.String(length=2), nullable=True),
    sa.Column('tid', sa.String(), nullable=True),
    sa.Column('tst', sa.Integer(), nullable=True),
    sa.Column('vac', sa.Integer(), nullable=True),
    sa.Column('vel', sa.Integer(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('poi', sa.String(), nullable=True),
    sa.Column('conn', sa.String(length=2), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('inregions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('inrids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('SSID', sa.String(), nullable=True),
    sa.Column('BSSID', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('m', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('general_loc_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_loc_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conn', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('inregions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('inrids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('SSID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('BSSID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('acc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cog', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('t', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('tid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tst', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('poi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('m', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='general_loc_data_pkey')
    )
    op.drop_table('location')
    # ### end Alembic commands ###
