"""some changes

Revision ID: f8e30574bd95
Revises: 95d0cb80745a
Create Date: 2023-08-19 14:46:18.228714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e30574bd95'
down_revision = '95d0cb80745a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
